### ISSUE TITLE
While deploying the docker-compose there are errors on the primus module as strict & const seem not compatible...

### ISSUE THREAD

**Issue by jmlambert78** [Capgemini-AIE/ethereum-docker#17]
I just launched the docker compose to run a cluster, and launching the eth-netstats is broken.
JMarc
/eth-netstats/node_modules/primus/index.js:177
    const sandbox = Object.keys(global).reduce((acc, key) => {
    ^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/eth-netstats/app.js:44:14)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)

npm ERR! Linux 3.13.0-52-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v0.12.17
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE
npm ERR! eth-netstats@0.0.9 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the eth-netstats@0.0.9 start script 'node ./bin/www'.
npm ERR! This is most likely a problem with the eth-netstats package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can g

**Comment by meken** [comment]
I had a similar issue, and fixed that by upgrading the node version for the eth-netstats container; updating the first line of the eth-netstats/Dockerfile from `FROM node:0.12` to `FROM node:7` did it for me.

**Comment by jmlambert78** [comment]
yes thx its fixed in my case as well, we should update the file and release...

**Comment by tayzlor** [comment]
Closing via https://github.com/Capgemini-AIE/ethereum-docker/pull/18
