### ISSUE TITLE
Password is missing

### ISSUE THREAD

**Issue by h2mch** [Capgemini-AIE/ethereum-docker#19]
I'm looking for the password of those 10 provided accounts. How can I find them?

**Comment by xixuejia** [comment]
Same question here. How can we use the account pre-created?

**Comment by betheone5** [comment]
Same questions here. Do you have a puzzle to find the password? .. pwd please

**Comment by betheone5** [comment]
If you have not figured it out yet. There is no password. it is empty string

**Comment by h2mch** [comment]
as @betheone5 mention: it is an empty string. An other option: Replaced the 10 provided accouts with self-made accounts - which I have done
