### ISSUE TITLE
"apt-get: not found" during Building bootstrap

### ISSUE THREAD

**Issue by professorgrumps** [Capgemini-AIE/ethereum-docker#24]
Hello, really interested in this project - was trying to get the following to work:

`$ docker-compose up -d`

but I get this:

> Creating netstats
> Building bootstrap
> Step 1 : FROM ethereum/client-go
>  ---> 4b290a5d5747
> Step 2 : RUN apt-get update &&    apt-get install -y curl git-core &&    curl -sL https://deb.nodesource.com/setup_4.x | bash - &&    apt-get update &&    apt-get install -y nodejs
>  ---> Running in 839ec68e0b63
> ←[91m/bin/sh: apt-get: not found
> ←[0m←[31mERROR←[0m: Service 'bootstrap' failed to build: The command '/bin/sh -c apt-get update &&    apt-get install -y curl git-core &&    curl -sL https://deb.nodesource.com/setup_4.x | bash - &&
>  apt-get update &&    apt-get install -y nodejs' returned a non-zero code: 127

please help!

**Comment by 2075** [comment]
you can try to split the last command into separate lines instead of combining them with &&, then you will see, which command will fail.

**Comment by chrc** [comment]
The Docker image ethereum/client-go is under the alpine image [(go-ethereum Dockerfile)](https://github.com/ethereum/go-ethereum/blob/master/Dockerfile)

Instead of **apt-get install**, you have to use **apk add**

**Comment by professorgrumps** [comment]
@2075 @chrc thanks a bunch, that got me further, but now I'm getting the following

```
Step 4 : RUN curl -sL https://deb.nodesource.com/setup_4.x | sh -
 ---> Running in 020b0b1bb707

## Installing the NodeSource Node.js v4.x LTS Argon repo...


## Populating apt-get cache...

+ apt-get update
Error executing command, exiting
```

I suspect its due to the 'apt-get' in this: https://deb.nodesource.com/setup_4.x
if that's so, is there an alpine / apk compliant node url? (sorry, *nix n00b)

**Comment by chrc** [comment]
Hi,

My monitored-geth-client/Dockerfile
```
FROM ethereum/client-go:latest

RUN apk update

RUN apk add curl git bash nodejs perl

RUN cd /root &&\
    git clone https://github.com/cubedro/eth-net-intelligence-api &&\
    cd eth-net-intelligence-api &&\
    npm install &&\
    npm install -g pm2

ADD start.sh /root/start.sh
ADD app.json /root/eth-net-intelligence-api/app.json
RUN chmod +x /root/start.sh

ENTRYPOINT /root/start.sh
```

**Comment by tayzlor** [comment]
This should be fixed in https://github.com/Capgemini-AIE/ethereum-docker/commit/cf23879c00f8bcc59f8ef7195e767adf6fc3979c , closing. Please re-open if there is an issue
