### ISSUE TITLE
How to unlock accounts placed in the keystore? 

### ISSUE THREAD

**Issue by DeRain** [Capgemini-AIE/ethereum-docker#35]
I've tried to log in via account placed in the key store and realized that i don't know the password. Then I've tried to seek password in the repository but unsuccessfully.

Could you add the password for the accounts in the keystore into readme file?

**Comment by LarsKoelpin** [comment]
Have you tried an empty password (""). Worked for me

**Comment by manojpramesh** [comment]
If you cannot find the password, create some accounts of your own and change the keyfiles accordingly.

If you need help, use this one - [keystore](https://github.com/manojpramesh/ethereum-docker/tree/master/files/keystore). Password - **Innov@teD@ily1**

**Comment by DeRain** [comment]
@LarsKoelpin i've tried in myetherwallet, but it's not allowing to use an empty strings.

**Comment by DeRain** [comment]
@manojpramesh Sure, I've created keystore with 10 accounts with the same password. Thank for the help to all!
